=begin
#Amadeus Travel Innovation Sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::CarrierInfo
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CarrierInfo' do
  before do
    # run before each test
    @instance = SwaggerClient::CarrierInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarrierInfo' do
    it 'should create an instact of CarrierInfo' do
      expect(@instance).to be_instance_of(SwaggerClient::CarrierInfo)
    end
  end
  describe 'test attribute "logos"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

