=begin
#Amadeus Travel Innovation Sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::HotelReservationBookingInfo
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HotelReservationBookingInfo' do
  before do
    # run before each test
    @instance = SwaggerClient::HotelReservationBookingInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HotelReservationBookingInfo' do
    it 'should create an instact of HotelReservationBookingInfo' do
      expect(@instance).to be_instance_of(SwaggerClient::HotelReservationBookingInfo)
    end
  end
  describe 'test attribute "reservation_code"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

