=begin
#Amadeus Travel Innovation Sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient

  class HotelRoom
    # The booking code identifies a product at the hotel. It can be used to book a room.
    attr_accessor :booking_code

    # A 3-letter code to identify a specific room type.
    attr_accessor :room_type_code

    # A 3 letter code to designate different rates base on traveler type.
    attr_accessor :rate_plan_code

    # The total price of staying in this room from the given check-in date to the given check-out date
    attr_accessor :total_amount

    # The total price of staying in this room from the given check-in date to the given check-out date
    attr_accessor :rates

    # An array of description strings describing room and rate types features
    attr_accessor :descriptions

    attr_accessor :room_type_info

    # The unique rate code used by the hotel chain to price this room's rate
    attr_accessor :rate_type_code


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'booking_code' => :'booking_code',
        :'room_type_code' => :'room_type_code',
        :'rate_plan_code' => :'rate_plan_code',
        :'total_amount' => :'total_amount',
        :'rates' => :'rates',
        :'descriptions' => :'descriptions',
        :'room_type_info' => :'room_type_info',
        :'rate_type_code' => :'rate_type_code'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'booking_code' => :'String',
        :'room_type_code' => :'String',
        :'rate_plan_code' => :'String',
        :'total_amount' => :'Amount',
        :'rates' => :'Array<PeriodRate>',
        :'descriptions' => :'Array<String>',
        :'room_type_info' => :'RoomInfo',
        :'rate_type_code' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'booking_code')
        self.booking_code = attributes[:'booking_code']
      end

      if attributes.has_key?(:'room_type_code')
        self.room_type_code = attributes[:'room_type_code']
      end

      if attributes.has_key?(:'rate_plan_code')
        self.rate_plan_code = attributes[:'rate_plan_code']
      end

      if attributes.has_key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      end

      if attributes.has_key?(:'rates')
        if (value = attributes[:'rates']).is_a?(Array)
          self.rates = value
        end
      end

      if attributes.has_key?(:'descriptions')
        if (value = attributes[:'descriptions']).is_a?(Array)
          self.descriptions = value
        end
      end

      if attributes.has_key?(:'room_type_info')
        self.room_type_info = attributes[:'room_type_info']
      end

      if attributes.has_key?(:'rate_type_code')
        self.rate_type_code = attributes[:'rate_type_code']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @booking_code.nil?
        invalid_properties.push("invalid value for 'booking_code', booking_code cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @booking_code.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          booking_code == o.booking_code &&
          room_type_code == o.room_type_code &&
          rate_plan_code == o.rate_plan_code &&
          total_amount == o.total_amount &&
          rates == o.rates &&
          descriptions == o.descriptions &&
          room_type_info == o.room_type_info &&
          rate_type_code == o.rate_type_code
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [booking_code, room_type_code, rate_plan_code, total_amount, rates, descriptions, room_type_info, rate_type_code].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
