=begin
#Amadeus Travel Innovation Sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient

  class TrainSearchPricing
    # A standard enumeration of the type of seat, bed or service the passenger can expect.
    attr_accessor :service_class

    # A code the identifies the type of booking class being used.
    attr_accessor :booking_code

    # A standard enumeration of the mode in which the passenger is accommodated. For example&colon; SEAT, BERTH, CABIN, CARGO, UNKNOWN.
    attr_accessor :accomodation

    # The total cost of this service.
    attr_accessor :total_price

    # A rate identifying type of charge being levied for this service, and the restrictions that apply.
    attr_accessor :rate


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'service_class' => :'service_class',
        :'booking_code' => :'booking_code',
        :'accomodation' => :'accomodation',
        :'total_price' => :'total_price',
        :'rate' => :'rate'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'service_class' => :'String',
        :'booking_code' => :'String',
        :'accomodation' => :'String',
        :'total_price' => :'Amount',
        :'rate' => :'RestrictedRate'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'service_class')
        self.service_class = attributes[:'service_class']
      end

      if attributes.has_key?(:'booking_code')
        self.booking_code = attributes[:'booking_code']
      end

      if attributes.has_key?(:'accomodation')
        self.accomodation = attributes[:'accomodation']
      end

      if attributes.has_key?(:'total_price')
        self.total_price = attributes[:'total_price']
      end

      if attributes.has_key?(:'rate')
        self.rate = attributes[:'rate']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @service_class.nil?
        invalid_properties.push("invalid value for 'service_class', service_class cannot be nil.")
      end

      if @booking_code.nil?
        invalid_properties.push("invalid value for 'booking_code', booking_code cannot be nil.")
      end

      if @accomodation.nil?
        invalid_properties.push("invalid value for 'accomodation', accomodation cannot be nil.")
      end

      if @total_price.nil?
        invalid_properties.push("invalid value for 'total_price', total_price cannot be nil.")
      end

      if @rate.nil?
        invalid_properties.push("invalid value for 'rate', rate cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @service_class.nil?
      return false if @booking_code.nil?
      return false if @accomodation.nil?
      return false if @total_price.nil?
      return false if @rate.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          service_class == o.service_class &&
          booking_code == o.booking_code &&
          accomodation == o.accomodation &&
          total_price == o.total_price &&
          rate == o.rate
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [service_class, booking_code, accomodation, total_price, rate].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
