=begin
#Amadeus Travel Innovation Sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/address'
require 'swagger_client/models/affiliate_flight_search_price'
require 'swagger_client/models/affiliate_payout'
require 'swagger_client/models/affiliate_search_meta'
require 'swagger_client/models/affiliate_search_response'
require 'swagger_client/models/affiliate_search_result'
require 'swagger_client/models/airport'
require 'swagger_client/models/airport_autocomplete_response'
require 'swagger_client/models/airport_information'
require 'swagger_client/models/amenity'
require 'swagger_client/models/amount'
require 'swagger_client/models/award'
require 'swagger_client/models/car_reservation'
require 'swagger_client/models/car_reservation_booking_info'
require 'swagger_client/models/car_search_response'
require 'swagger_client/models/car_search_result'
require 'swagger_client/models/carrier_info'
require 'swagger_client/models/carrier_meta'
require 'swagger_client/models/city_information'
require 'swagger_client/models/company'
require 'swagger_client/models/contact'
require 'swagger_client/models/error'
require 'swagger_client/models/extensive_train_search_response'
require 'swagger_client/models/extensive_train_search_result'
require 'swagger_client/models/extreme_search_response'
require 'swagger_client/models/extreme_search_result'
require 'swagger_client/models/fare'
require 'swagger_client/models/fare_restrictions'
require 'swagger_client/models/fees'
require 'swagger_client/models/flight_reservation_booking_info'
require 'swagger_client/models/flight_reservation_bound'
require 'swagger_client/models/flight_reservation_segment'
require 'swagger_client/models/flight_search_booking_info'
require 'swagger_client/models/flight_search_bound'
require 'swagger_client/models/flight_search_itinerary'
require 'swagger_client/models/flight_search_price'
require 'swagger_client/models/flight_search_segment'
require 'swagger_client/models/flight_ticket'
require 'swagger_client/models/flight_traffic_search_result'
require 'swagger_client/models/frequent_traveler_card'
require 'swagger_client/models/geolocation'
require 'swagger_client/models/hotel_property_response'
require 'swagger_client/models/hotel_reservation'
require 'swagger_client/models/hotel_reservation_booking_info'
require 'swagger_client/models/hotel_room'
require 'swagger_client/models/hotel_search_response'
require 'swagger_client/models/image'
require 'swagger_client/models/image_size'
require 'swagger_client/models/infant'
require 'swagger_client/models/link'
require 'swagger_client/models/location_response'
require 'swagger_client/models/logos'
require 'swagger_client/models/low_fare_search_response'
require 'swagger_client/models/low_fare_search_result'
require 'swagger_client/models/message'
require 'swagger_client/models/nearest_airport'
require 'swagger_client/models/other_reservation'
require 'swagger_client/models/other_reservation_booking_info'
require 'swagger_client/models/period_rate'
require 'swagger_client/models/point_of_interest_city'
require 'swagger_client/models/point_of_interest_details'
require 'swagger_client/models/point_of_interest_result'
require 'swagger_client/models/point_of_interest_result_grades'
require 'swagger_client/models/points_of_interest_response'
require 'swagger_client/models/rail_service'
require 'swagger_client/models/rail_station_autocomplete_response'
require 'swagger_client/models/rail_station_response'
require 'swagger_client/models/rate'
require 'swagger_client/models/reservation'
require 'swagger_client/models/restricted_rate'
require 'swagger_client/models/room_info'
require 'swagger_client/models/station'
require 'swagger_client/models/top_destinations_search_response'
require 'swagger_client/models/top_destinations_search_result'
require 'swagger_client/models/top_searches_search_response'
require 'swagger_client/models/top_searches_search_result'
require 'swagger_client/models/train_schedule_search_response'
require 'swagger_client/models/train_schedule_search_result'
require 'swagger_client/models/train_search_itinerary'
require 'swagger_client/models/train_search_pricing'
require 'swagger_client/models/train_search_segment'
require 'swagger_client/models/travel_record_header'
require 'swagger_client/models/travel_record_response'
require 'swagger_client/models/traveler'
require 'swagger_client/models/vehicle'
require 'swagger_client/models/vehicle_info'

# APIs
require 'swagger_client/api/default_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
